url: http://freifunk.in-kiel.de/

community:
  # Metadata
  name: "Kiel"
  meta: "Freifunk Nord"
  country: "DE"

  # Custom URLs
  url_wiki:  "http://wiki.freifunk.in-kiel.de/"

  url_geomap: "http://map.freifunk.in-kiel.de/"
  url_graph: "http://graph.freifunk.in-kiel.de/"
  url_nodelist: "http://alfred.freifunk.in-kiel.de/"

  url_mailman: "http://lists.in-kiel.de/cgi-bin/mailman/listinfo/freifunk"

  url_firmware: "http://freifunk.in-kiel.de/firmware.html"

  # Mail Contacts
  mail_info: "freifunk@in-kiel.de"
  mail_keys: "freifunk-keys@in-kiel.de"
  mail_discussion: "freifunk@in-kiel.de"

  # Other Contacts
  #sip: ["space@sip.ffki"] # Optional
  twitter: "ff_Kiel" # Optional
  irc: "ffki"

  # GPS
  geo_lat: 54.4
  geo_lon: 10.1

firmware:
  base: "http://freifunk.in-kiel.de/firmware/stable/"
  type: "gluon"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/sargon/site-ffki"
  # Path to local checkout of the site repo
  gluon_site_dir: "/opt/site-ffki/"

tld:
  label: "ffki"
  ns:
    - "10.116.128.1"
    - "fda1:384a:74de:4242::1"
    - "10.116.136.1"
    - "fda1:384a:74de:4242::5"
    - "10.116.144.1"
    - "fda1:384a:74de:4242::8"
    - "10.116.152.1"

