url: http://freifunk.localhost/

community:
  # Metadata
  name: "Nord"
  meta: "Freifunk Nord"
  country: "DE"

  # Custom URLs
  url_wiki:  "http://wiki.freifunk.net/Freifunk_Nord/"

  url_geomap: "http://mesh.nord.freifunk.net/"
  url_graph: "http://mesh.nord.freifunk.net/"
  url_nodelist: "http://nord.freifunk.net/numnodes.html/"

  url_mailman: "http://lists.freifunk.net/mailman/listinfo/ffnord-freifunk.net"

  url_firmware: "http://nord.freifunk.net/firmware.html"

  url_blog_cms: "https://github.com/ffnord/nord-blog"

  # Mail Contacts
  mail_info: "ffnord@freifunk.net"
  mail_keys: ""
  mail_discussion: "ffnord@freifunk.net"

  # Other Contacts
  #sip: ["space@sip.ffki"] # Optional
  twitter: "FreifunkNord" # Optional
  irc: "ffnord"

  # GPS
  geo_lat: 54.0
  geo_lon: 10.0

firmware:
  #base: "https://freifunk.in-kiel.de/firmware/stable/"
  base: "http://gluon.ffki.de/ffnord/0.7.2/"
  #base: http://localhost/freifunk/firmware/ffki/0.7.1/"
  #base: "http://gluon.ffki.de/firmware/stable/"
  #base: "http://freifunk.discovibration.de/firmware/firmware-0.7.1/"
  type: "gluon"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/ffnord/site-ffnord/"

  # Path to local checkout of the site repo
  gluon_site_dir: "/opt/site-ffnord/"

tld:
  label: "ffnord"
  ns:
    - "10.187.160.1"
    - "2a03:2267:4e6f:7264::01"
